import "./globals.css";
import { Navbar } from "../components/Navbar";
import Footer from "../common/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased m-0">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
