import "./globals.css";
import { Navbar } from "../common/Navbar";
import Footer from "../common/footer";
import SmoothScroll from "../common/SmoothScroll";
import SplashOverlay from "../common/SplashOverlay";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased m-0 bg-white " >
        <SplashOverlay />
        <SmoothScroll />
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
